name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"			#d1数据库绑定名默认不可修改
database_name = "cloud-email"		#d1数据库名字
database_id = "d7b13ee5-2417-4e89-b4d8-4e192ac8cbdb"		#d1数据库id

[[kv_namespaces]]
binding = "kv"			#kv绑定名默认不可修改
id = "5f8107a6bf5b4ec0915b015ac7130b37"					#kv数据库id

[[r2_buckets]]
binding = "r2"			#r2对象存储绑定名默认不可修改
bucket_name = "cloud-email"		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
orm_log = true
domain = ["bkui.cn","nakeu.cn","nankoyo.cn","nankoyo.com","smart-pages.cn","vallengine.cn","email.nankoyo.com"]				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
admin = "admin@email.nankoyo.com"				#管理员的邮箱	示例: admin@example.com
jwt_secret = "Z7nxPq8mVL2bCr9XN1C"			#jwt令牌的密钥,随便填一串字符串
linuxdo_client_id = "S48Pal6AkeNkLIN48nPv9ruAGJiiYUYP"
linuxdo_client_secret = "xcxoARTyeILCYEzH59lGloUtze9NW2sa"
linuxdo_callback_url = "https//mail.nankoyo.com/login"
linuxdo_switch = "true"



[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
